@startuml frontend
Title Frontend Architecture

!include ./frontend-classes.puml

EventHandler -down-> ChartWrapper
EventHandler -down-> ButtonWrapper
EventHandler -down-> FromWrapper
EventHandler -down-> TableManager
EventHandler -down-> ToastWrapper

@enduml