@startuml on-end-request-flexibility-event
title On EndRequestFlexibility Event

!include ./participants.puml

'New RequestFlexibility event for IoT
iot <- ewc ++ : **RequestFlexibility**
iot -> iot : //confirmProvidedFlexibility//
iot -> ewc : //provideFlexibilityFair//
note over iot : Remove the **FlexibilityEvent**

@enduml