@startuml on-request-flexibility-event
' title On RequestFlexibility Event

!include ./participants.puml


'New RequestFlexibility event for IoT
iot <- ewc ++ : **RequestFlexibilityEvent**
iot -> iot ++: //provideFlexibility//
note over iot : A new **FlexibilityEvent** is created and will be considered in the production cycle
deactivate iot
deactivate iot

@enduml