/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { IoTBank, IoTBankInterface } from "../IoTBank";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable[]",
        name: "iotAddr",
        type: "address[]",
      },
    ],
    name: "sendFunds",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610375806100206000396000f3fe60806040526004361061001e5760003560e01c8063ff86055814610023575b600080fd5b61003d60048036038101906100389190610156565b61003f565b005b60008282905034610050919061020b565b905060005b838390508110156100e1578383828181106100735761007261023c565b5b905060200201602081019061008891906102c9565b73ffffffffffffffffffffffffffffffffffffffff166108fc839081150290604051600060405180830381858888f193505050501580156100cd573d6000803e3d6000fd5b5080806100d9906102f6565b915050610055565b50505050565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f840112610116576101156100f1565b5b8235905067ffffffffffffffff811115610133576101326100f6565b5b60208301915083602082028301111561014f5761014e6100fb565b5b9250929050565b6000806020838503121561016d5761016c6100e7565b5b600083013567ffffffffffffffff81111561018b5761018a6100ec565b5b61019785828601610100565b92509250509250929050565b6000819050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000610216826101a3565b9150610221836101a3565b925082610231576102306101ad565b5b828204905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006102968261026b565b9050919050565b6102a68161028b565b81146102b157600080fd5b50565b6000813590506102c38161029d565b92915050565b6000602082840312156102df576102de6100e7565b5b60006102ed848285016102b4565b91505092915050565b6000610301826101a3565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff821415610334576103336101dc565b5b60018201905091905056fea2646970667358221220cba9cce0e6f81e8121ce1693b8087cba36d3c767a5ca9aa8d84efca4783dc83c64736f6c63430008090033";

type IoTBankConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IoTBankConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class IoTBank__factory extends ContractFactory {
  constructor(...args: IoTBankConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<IoTBank> {
    return super.deploy(overrides || {}) as Promise<IoTBank>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): IoTBank {
    return super.attach(address) as IoTBank;
  }
  override connect(signer: Signer): IoTBank__factory {
    return super.connect(signer) as IoTBank__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IoTBankInterface {
    return new utils.Interface(_abi) as IoTBankInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IoTBank {
    return new Contract(address, _abi, signerOrProvider) as IoTBank;
  }
}
