name: Electron app release

on:
  push:
    branches: [master]
    paths:
      - simulator/**

  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Remove dependencies
        run: |
          rm package.json
          rm package-lock.json

      - name: Install dependencies - Contracts
        run: npm install
        working-directory: contracts

      - name: Install dependencies - Simulator
        run: |
          npm install
          npm i -D @nomicfoundation/hardhat-toolbox @nomiclabs/hardhat-ethers
        working-directory: simulator

      - name: Compile the smart contracts
        run: npm run compile
        working-directory: contracts

      - name: Package electron
        run: npm run package
        working-directory: simulator

      - name: Upload the artifact - Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: EW-IoT-Simulator-linux-x64
          path: simulator/EW IoT Simulator-linux-x64/

      - name: Upload the artifact - MacOs
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: EW-IoT-Simulator-darwin-x64
          path: simulator/EW IoT Simulator-darwin-x64/

      - name: Upload the artifact - Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: EW-IoT-Simulator-win32-x64
          path: simulator/EW IoT Simulator-win32-x64/
